### ISSUE TITLE
Testing code still left there

### ISSUE THREAD

**Issue by appgurueu** [PolySaken-I-Am/guidebooklib#1]
See [here](https://github.com/PolySaken-I-Am/guidebooklib/blob/master/init.lua#L315).
It should only be used by devs and not be in the releases. I recommend you to comment it out (or move it to a different file/mod).

**Comment by PolySaken-I-Am** [comment]
Fair point I'll remove it when i find the time.

**Comment by PolySaken-I-Am** [comment]
Since the most recent fatal bug has finally been solved I had time to remove the test code. It should be gone in the newest release.
